### ISSUE TITLE
Player get kicked when hitting other user.

### ISSUE THREAD

**Issue by HueZuX** [Crazy-Crew/Block-Particles#16]
I searched for the problem but it figured out that it is due Blockparticles.

When a player on my server is hitting someone else they get kicked and the reason my console or they get when they got kicked is:

Internal Exception: java.lang.NoSuchFieldError: v1_14_R1

Please fix this because I really like your plugin but this is not gonna work for me, I don't know if there are any other users having the same problem.

**Comment by badbones69** [comment]
Can u pastebin the full error log for me.

**Comment by badbones69** [comment]
Have u tried updating to the new BP and check if it still doses it.

**Comment by Mxtchhel** [comment]
I tried the new update Yesterday but it still does unfortunately

**Comment by badbones69** [comment]
do /version and tell me what it shows.

**Comment by badbones69** [comment]
I loaded up a 1.13.2 server and punched my alt and its working fine.

**Comment by Mxtchhel** [comment]
Oh that's weird then, idk exactly why it's causing that for me.

/version:
![image](https://user-images.githubusercontent.com/41380131/61595116-7469bc80-abf3-11e9-9e9a-404633bb1552.png)


And idk if its due one of my plugins, I'll send you the list with plugins I have.
![image](https://user-images.githubusercontent.com/41380131/61595123-8cd9d700-abf3-11e9-9a62-b1dd56c710ef.png)
