### ISSUE TITLE
Item Frame kick no such field

### ISSUE THREAD

**Issue by MrMathias154** [Crazy-Crew/Block-Particles#21]
The error: lost connection: Internal Exception: java.lang.NoSuchFieldError: v1_14_R1.

https://hasteb.in/xegezuro.md
Isolated logs only: https://hasteb.in/iyuxeyib.md

Run in version:
Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Viaver:  ViaVersion v2.2.3-SNAPSHOT
Block-Particles version v1.11.1-RELEASE **
minecraft in 1.14.4 **

Additional info:
BungeeCord: true
late-bind: true

After sometest is isolated your plugins , and the only one kick him out of the servers.

**Comment by MrMathias154** [comment]
Block-Particles version v1.11.1-RELEASE **

**Comment by MrMathias154** [comment]
minecraft in 1.14.4 **

**Comment by badbones69** [comment]
Can you repost the log as nothing is showing when I click the link.

**Comment by RyderBelserion** [comment]
Old bug.
