### ISSUE TITLE
Particle Bugs - Incompatible

### ISSUE THREAD

**Issue by AccioAce** [Crazy-Crew/Block-Particles#24]
Hello, it seems like Block Particles is incompatible with 1.16.5 version. When ever I setup a particle it's all the same particle and only white color ->  https://gyazo.com/705f85a9dfca745ea5bcb6d2e7719285

I don't see any console errors popping up either. So I block particle just need 1.16.5 support.

My server version: 1.16.5
Block Particle Version: BlockParticles[v1.12]

**Comment by RyderBelserion** [comment]
Added to project board.
